### ISSUE TITLE
Eager loading

### ISSUE THREAD

**Issue by kwent** [instacart/amountable#14]
Hi there,

The following line is causing the library to not lazy load. https://github.com/instacart/amountable/blob/6106c1a0be5e3dbe449d30f77b741b0298eba734/lib/amountable.rb#L74

Regards

**Comment by Matt-Hurd** [comment]
cc: @neutralino1

**Comment by kwent** [comment]
I believe this has been fixed with https://github.com/instacart/amountable/commit/469951bd71e6788ef8499ac74787f2137207daa3.

Thanks ! Closing...
