### ISSUE TITLE
Compatibility with Rails 5.1.4

### ISSUE THREAD

**Issue by kulte** [instacart/amountable#9]
Currently, the gemspec requires lt 5.1, not sure why, but it seems like that can be removed and bumped to the latest. Also, could we cut a new version on Rubygems, as opposed to having to grab from git. The current version is for ~> 4.1!

**Comment by kulte** [comment]
There's also a new version of `activerecord-import` so you might want to bump that to `~> 0.20.0` as well.

**Comment by mlarraz** [comment]
Closed due to staleness (and these issues being resolved already)
